name: build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: AWS CLI 설치
        uses: unfor19/install-aws-cli-action@master
      - name: AWS HELP 명령어 테스트
        run: aws ecs help
      - name: ECS 배포 테스트
        run: |
          aws ecs update-service --cluster automl-cluster --service automl-service --task-definition automl-main-web-task-definition:10 --force-new-deployment
